# Generated by Django 3.2.9 on 2021-12-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0003_organisationentity_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgChartURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('url', models.URLField()),
                ('organisation_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgcharts', to='organisation.organisationentity')),
            ],
        ),
        migrations.CreateModel(
            name='OrgChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('document_hash', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='')),
                ('org_chart_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgcharts.orgcharturl')),
            ],
        ),
    ]
