# Generated by Django 3.2.9 on 2021-12-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgcharts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orgchart",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
