# Generated by Django 3.2.9 on 2021-12-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orgcharts", "0002_alter_orgchart_created_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orgchart",
            unique_together={("org_chart_url", "document_hash")},
        ),
    ]
