# Generated by Django 3.2.9 on 2021-12-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgcharts', '0004_auto_20211212_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgchart',
            name='status',
            field=models.CharField(choices=[('NEW', 'new'), ('PARSED', 'parsed'), ('IMPORTED', 'imported')], default='NEW', max_length=20),
        ),
    ]
