# Generated by Django 3.2.9 on 2021-12-18 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0003_organisationentity_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=5)),
                ("country", models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name="organisationentity",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="organisation.organisationentity",
            ),
        ),
        migrations.AddField(
            model_name="organisationentity",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="organisations",
                to="organisation.OrganisationAddress",
            ),
        ),
    ]
