# Generated by Django 3.2.10 on 2022-01-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0004_auto_20211218_0113"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationaddress",
            name="phone_prefix",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
