# Generated by Django 3.2.10 on 2022-01-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0007_alter_organisationaddress_street"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationaddress",
            name="postal_code",
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
