# Generated by Django 3.2.10 on 2022-01-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0008_alter_organisationaddress_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationaddress",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
