# Generated by Django 3.2.9 on 2021-12-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimtype',
            name='content_type',
        ),
        migrations.AddField(
            model_name='claimtype',
            name='content_type',
            field=models.ManyToManyField(to='contenttypes.ContentType'),
        ),
    ]
