# Generated by Django 3.2.9 on 2021-12-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0004_auto_20211203_2032"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valueclaim",
            name="value",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
