# Generated by Django 3.2.9 on 2021-12-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0005_alter_valueclaim_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimtype",
            name="value_schema",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
