# Generated by Django 3.2.9 on 2021-12-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0006_alter_claimtype_value_schema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="valueclaim",
            name="value",
        ),
        migrations.AddField(
            model_name="claim",
            name="value",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
