# Generated by Django 3.2.9 on 2021-12-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_auto_20211204_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimtype',
            name='code_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
