# Generated by Django 3.2.12 on 2022-03-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0008_claimtype_code_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimtype",
            name="value_template",
            field=models.TextField(blank=True, null=True),
        ),
    ]
