"""
Django settings for settings project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@_)sfbt%39%85=#i0-)7p04gvuu-o@a%6i@3c9tlc^-r(57&@*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'polymorphic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'reversion',
    'django_admin_json_editor',
    'graphene_django',

    # Serious Django
    "serious_django_services",
    "serious_django_permissions",

    'oauth2_provider',
    'oauth2_provider_jwt',
    "crispy_forms",
    # cors
    "corsheaders",

    'organisation',
    'person',
    'claims',
    'orgcharts',
    'oauth',

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsPostCsrfMiddleware",
    "oauth2_provider.middleware.OAuth2TokenMiddleware",
]

AUTHENTICATION_BACKENDS = (
    "oauth.oauth_backend.OAuth2Backend",
    "django.contrib.auth.backends.ModelBackend",
    "serious_django_permissions.permissions.PermissionModelBackend",
    "guardian.backends.ObjectPermissionBackend",
)



# Serious Django configuration
DEFAULT_GROUPS_MODULE = "settings.default_groups"

OAUTH2_PROVIDER = {
    "SCOPES": {
        "administrative-staff": "Administrative Staff",
    },
}

GRAPHENE = {
    "SCHEMA": "settings.schema.schema",
    'RELAY_CONNECTION_MAX_LIMIT': 1000,
}

ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR.joinpath("settings/templates"))],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

STATICFILES_DIRS = ("settings/static/",)


# TODO: move this to config
JWT_ISSUER = "STRUKTUREN"
JWT_ENABLED = True
JWT_ID_ATTRIBUTE = "email"
JWT_PRIVATE_KEY_STRUKTUREN = """
-----BEGIN RSA PRIVATE KEY-----
MIIJJwIBAAKCAgEApZDxqhI8O93V0LGwAiQqYR1n2PPeby7DbvrE3yd4zWgw5Rxe
3SnmzXH2t+Q0O3OSsH5y19ZeDgfyRX74REr+bPW0Mkg99POAJWmXZF6XyWEKWETJ
4I+/sK5jySOMOA6Bc+eSPoPtQTjUdI7zLk/XXPlzid6LveRqPinj4LpO4yHmN6tF
RQPG6dZ/gIshCONoS/YZLeYUhQIGSuL7zNJTldcXhKRXcZ5iqW+v4DlNtuzCLGlZ
tLnu33H9cHmW9kWxbdMB0a6Jf/x8I8X3g3Cbu1pcDduDrRtDgkrYq4UDFT07UlpR
iGZ3lHtK/48aYu0CnsglVEIpku4S85IAOYWTz9D1yjIkTWXauaywGXsUPcf2/mlE
MiclXonynoY0ixR9IxbWCBr2XxeiyCaYx0xzP9dPrVIyhZRgbZXfM5CHRexlUWwW
AifvfJfEjDVq76SqwYr70Ta1aMRIYMb90ojmaHyRKOR+KGHAJb2T32sC9FNMb0EL
ksN1vZRahYhUtDBUZLvf9iBVXEGOiVCj1J12AvoGz6mX8IYWqpD9ldl+i17PeD+r
W5+TgsNj/IzY2AnvIp4+rcozzqaOt10KvdItEO9JWOEdqNI8fJ+M6MREFLg+driU
tw4CODTozIIfl6GpJzbHxSWcKdmp348IogXHFd8TQgdXEtO1jQ3Npo82IIcCAwEA
AQKCAgAC1aJtiPZjB/87HW+n+bqIAxreCf7K5IAQDFcGgwR8b8Y2he/R1X/QEJ1q
tIt4YRgn0WJh85eUoeox6mSRtr74WpSFL9tvsCOHgHFJFJ2AoxqsPDFAmPVtLu8i
aGtkIktxEovcaiHLtg9dF31uU4uaWeLyf07hJ2HyQoFWPZpQJSpt1Y7QCaqEIln4
d2lPX6VPd50ivgen50r4ST6KWSd5Lz+F09JzbYS+5dya+CAue4sve3Y/s9c1GByA
qnQ9LyBEgxJK5rQP7uCpNCByraDc6kUdL57nfcoAFwvyk8pjuLKlTEqNDUQK1LmJ
+oc3HlunIEITWTag/1ZvuRYr5e+L3jhM46GgxLgNolNUxUHrxBPLl/FoFTe3vL6E
hzHYjZylLX+XA3t3NHphCsCR1UYJdyxiqfYqrkDNkfcMMooIUdc2biQtaM6OB51u
F1p/e2VcWFzJnN7aCmMYjv2KitiVkkT3koIDr4VinUB8G+KUgcUqeI0QPO8Q99iA
ROhxNaky/Q/GjZR4Re6kFh6olF920QG0rCUckslferMpKrII7ZEJ4kuW90PFY6Py
kjMiOXkZmhUFzIFh8wzqAfbqqqCjiJgplEwax2UATv6ykSDAMbCkfPDTTUTr9Xji
kTrDUkMhEg/wNTE9c+Icf4HQl+OO3IRtsfKrGowEmBkG9veJsQKCAQEA1PV3Z4Bo
2L31mYxNh6deEZU4whY6hDLOMvU4zoyCbeKbVl7RzF1/xZqLtTmmDqPkgbyHyvP9
lAipmG0sAifsuoaVPk1bvFf9i1fi4YW8yFRo5fJRjstja5Cid6d+JGECMdPxbbKv
JxfRGayPDPWaiDwTgTClZOk3SdWs5xUCEtGwnJ3Yt2hZoa+JWlpH5SEU8fsZSCoJ
5eLixaoadJOf8kMv2tTO7mBPpLdu/N+D4IYsMT4EK+C96XIJCB7nVcz6rrowCmB9
o8RE3X8GD0tS3u0vVe5IfQbptLF+smuuKANFbAtboD2F7KF69QMppYaBPGh+9qTF
RSKHOSB6cinuLQKCAQEAxwdfIMSoPJx1Cyl6lxbZx9KPaOQJSncjLAltimUC150W
jLm4HakksfS5N/Z/R+D8JFNMPKxcGRoznXnAAcVesx4aVG7bITfuz2ZXAojUbM0M
9RemhZVkb7stol28za0BP6oWRZsPAr2/Ro/YRMwBpFnFrp733ZEcNwSXgoM0mf6t
N7nCv2UO2odhcVNt6SYc7QDVcegIatL6bhbSIRtgVb08OZtlQMZxxWKUX6un/NgP
td9gtrJVi6Gv9OGnlotmvamWQK3dQ4LH9WPGdFQtcRV1kc79YBqDWFKss5AxV1IR
5A9m+zpxeTmW4oGRiqf+8VFF8goiYoLKe1KTs4VuAwKCAQAPaYBtvi5YWU8YAL5v
rd4x+ZG1AjTT8nVX3MVytVqPJ1JEqvIWD0I7A9dOk1CASL414XYWaxgUCZh0jpob
wdXxHeJZMvILrHaOChtCZRJnkSxST/o1EmUsmLgZXsbTTS4CeytC3Cau9ptMd1+W
+YNojqh+tg2SQwqcTlmIE84lnIVioE3Z4DR0bibLojMH0yAX7ytCPMCgoY317jyh
6TkvKEujU7lyKQg6jIf8xxRdQHicS7ezkT1NUtJygwINBJuz34ewiJEvM/oj6Zh/
rNzfg1zkpC0c1048pIfd08sz3CC/FAdajnlNydYDO2pdL2HVBF8D7KLWQQx2RvJ1
prE1AoIBAH5DzfTy7ixtsc9gBDbgN0+O5I5NxRsp0/V3Ebhv9sqlDQ5AMG8YxH/l
WrAHQJ5wPGYrNj1zt4XxWnd4Kvi0pyyJV3jjTz+WxXlsWpzwA5v2xlajJ3Ct4ycD
H6NXRpVRQW6LUE/eXDqH+FYiobibmBsVHNV4YpV9HuJEln4lEPT1XhzxS3yy9yZq
JsaHgD4egNFW6xK1esmSiW/YKHz6ajZatF9zl1vtyXXI4YqEUzGUPPtL+IZPQvgv
nnqDwhc+3vJKKVllM+9Fg+fI4bkhQibwz0Kuh441o8gfwxKz0qmsFk+R+eo+HIkk
oPWX76aAh7u+rNot1bybbyunqq6EYtMCggEASBvl/hjmmc5AJFtLr8K8r8z54KOI
aVKLMQJsVzXy1k/Wn9cZ/rUt74ZFv+Rzleek6vUgnH7hJR7Jc0jT9Zy/mJLf0dV8
rJ6+xUR/3WbwpRmRxQ5R9yJSEVOtnwh33Qapp2CjpuxjiNmInaVO+F2OW5Nfdnkx
IrGFpZcsWDkZjzP2BJ6q8ae7OPFnS7y/mdR2jP70hRzK3s80hUOhE4jTW4Bx3s9h
zk4Pp0F18eXoTAJ6w+YEavx3ZXjHGX01rOFkO6oV0d1/8YK8+coChdpLN5zeCeYs
ch3Z68wWkLXmLCNvfEPgbB0J83avh8DpwMQamRgh3auUvO1Phuyilge1Bw==
-----END RSA PRIVATE KEY-----
"""


JWT_PUBLIC_KEY_STRUKTUREN = """
-----BEGIN RSA PUBLIC KEY-----
MIICCgKCAgEApZDxqhI8O93V0LGwAiQqYR1n2PPeby7DbvrE3yd4zWgw5Rxe3Snm
zXH2t+Q0O3OSsH5y19ZeDgfyRX74REr+bPW0Mkg99POAJWmXZF6XyWEKWETJ4I+/
sK5jySOMOA6Bc+eSPoPtQTjUdI7zLk/XXPlzid6LveRqPinj4LpO4yHmN6tFRQPG
6dZ/gIshCONoS/YZLeYUhQIGSuL7zNJTldcXhKRXcZ5iqW+v4DlNtuzCLGlZtLnu
33H9cHmW9kWxbdMB0a6Jf/x8I8X3g3Cbu1pcDduDrRtDgkrYq4UDFT07UlpRiGZ3
lHtK/48aYu0CnsglVEIpku4S85IAOYWTz9D1yjIkTWXauaywGXsUPcf2/mlEMicl
XonynoY0ixR9IxbWCBr2XxeiyCaYx0xzP9dPrVIyhZRgbZXfM5CHRexlUWwWAifv
fJfEjDVq76SqwYr70Ta1aMRIYMb90ojmaHyRKOR+KGHAJb2T32sC9FNMb0ELksN1
vZRahYhUtDBUZLvf9iBVXEGOiVCj1J12AvoGz6mX8IYWqpD9ldl+i17PeD+rW5+T
gsNj/IzY2AnvIp4+rcozzqaOt10KvdItEO9JWOEdqNI8fJ+M6MREFLg+driUtw4C
ODTozIIfl6GpJzbHxSWcKdmp348IogXHFd8TQgdXEtO1jQ3Npo82IIcCAwEAAQ==
-----END RSA PUBLIC KEY-----
"""

ML_BACKEND_BASE_URL = "http://127.0.0.1:8090"

WSGI_APPLICATION = 'settings.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# claims that are used in the code
CLAIMS = {
    "LEADS": "leads"
}

# Base url to serve media files
MEDIA_URL = '/media/'

# Path where media is stored
MEDIA_ROOT = os.path.join(BASE_DIR, 'dev_media/')


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

CORS_ALLOW_ALL_ORIGINS = True

LANGUAGE_CODE = "de-DE"

from django.utils.translation import ugettext_lazy as _

LANGUAGES = (
    ("en-US", _("English")),
    ("de-DE", _("German")),
)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
CRISPY_TEMPLATE_PACK = "bootstrap4"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
