# Generated by Django 3.2.11 on 2022-02-05 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0003_personposition_positionabbreviation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="person.positionabbreviation",
            ),
        ),
    ]
