# Generated by Django 3.2.12 on 2022-03-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0005_alter_person_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="personposition",
            name="female_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personposition",
            name="gender_neutral_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
