# Generated by Django 3.2.12 on 2022-03-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0006_auto_20220327_0940"),
    ]

    operations = [
        migrations.AddField(
            model_name="personposition",
            name="plural_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
