# Generated by Django 3.1.5 on 2021-02-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("en-US", "English"), ("de-DE", "German")],
                default="en-us",
                max_length=20,
            ),
        ),
    ]
